### ISSUE TITLE
Custom 404 Page Server Under Maintenance 

### ISSUE THREAD

**Issue by Circuit-Overtime** [Circuit-Overtime/elixpo_ai_chapter#21]
# Issue: Create Custom 404 and Server Maintenance Pages

## Description
We need to design and implement two custom error pages:
1. **Server Under Maintenance Page**: To be used when the server is down for maintenance.

These pages should be consistent with the design language of the rest of the application and provide a clear, user-friendly message. 

### 1. Custom 404 Page
- **Message**: The 404 page should include a friendly error message, such as:
  - "Oops! The page you're looking for can't be found."
  - "It seems like you’ve hit a dead end. Try going back to the home page."
- **Design Elements**:
  - Include a **Home** button that redirects to the homepage.
  - Optionally, feature an illustration or animation to make the page feel more lively and fun.
- **Responsive**: The page should be mobile and desktop-friendly.
  
### 2. Server Under Maintenance Page
- **Message**: Inform users that the server is under maintenance with a message like:
  - "We'll be back soon! Our servers are currently under maintenance."
  - "Sorry for the inconvenience. We're working on improvements and will be back shortly."
- **Design Elements**:
  - Add a countdown timer or estimated time to return, if possible.
  - Include social media links or contact information to keep users informed.
- **Responsive**: Ensure the page works well on different devices.

## Acceptance Criteria:
- The 404 and Maintenance pages must be visually consistent with the app’s design.
- Pages should clearly communicate the issue and provide easy navigation (for 404) or information (for maintenance).
- Test the pages for responsiveness on mobile, tablet, and desktop screens.

## Additional Notes:
- Consider using SVGs, illustrations, or icons for visual engagement.
- Use semantic HTML and ensure accessibility compliance (e.g., proper alt text for images).
  
### Suggestions:
- We can use libraries like **Bootstrap** or **Tailwind CSS** to speed up the design.
- Optionally, add a custom illustration for the 404 page that reflects our brand personality.
  
Feel free to suggest any ideas to improve the user experience of these error pages!

**Comment by vatsal-afk** [comment]
Hi! I am interested to work on this issue, could you please assign this to me

**Comment by Circuit-Overtime** [comment]
> Hi! I am interested in working on this issue, could you please assign this to me

Hi Vastal, yup I can Issue this to you! 
# 404 Page Development Guideline

Please follow the steps below to ensure consistency and adherence to project standards.

## Instructions

1. **File Structure**:  
   - Create a separate `.html` file for the 404 error page.
   - Use **Tailwind CSS** to style the page and maintain a clean and minimal design.

2. **Cartoon-style 404 Image**:
   - Use the [Elixpo Art Generator](https://circuit-overtime.github.io/Elixpo_ai_pollinations/elixpoArtGenerator.html) to create a cartoon-like 404 image.
   - Ensure the image aligns with the overall aesthetic of the page.

3. **Page Design**:
   - Make the page look **classy and professional**.
   - Avoid clutter, and ensure the design is **responsive** across devices.

4. **Home Button**:
   - Add a **Home button** that redirects the user to the `elixpo_homepage.html`.
   - Ensure the button is prominent and easy to identify.
   - You can use a logo from ion-icon or font-awesome

**Comment by vatsal-afk** [comment]
hey @Circuit-Overtime! what do you think about this? 
![image](https://github.com/user-attachments/assets/c7695861-db43-4c86-9173-9c5f7778c2f6)

the design matches with the homepage, pls leave your suggestions for improvements :) also I've use your tool to generate the cartoon

**Comment by Circuit-Overtime** [comment]
Hello Vastal, I really like the design and it suits with the theme of the website -- you can change the font-family to [VT323](https://fonts.google.com/specimen/VT323). 

### Additionally there's a change of request -- keep the text as  `Server Under Maintenance -- Check back Later` since GitHub hosting is giving the 404 for us so change the code to `503`

- the visuals the attractive and i highly appreciate the design
- you can create a `PULL REQUEST` from this issue and wait for approval (ETA a few hours)
- provide me with your official `email address` since you will receive a badge through `badgr canvas` after an approved pull request (you will be able to showcase the badge in your GitHub readme or website using the share section `HTML` code provided by badgr) and your `LinkedIn` (if any)

**welcome to elixpo_ai_chapter** as a contributor!

**Comment by Circuit-Overtime** [comment]
Alright Vastal, I have received the PR, you need not make any other change to the site and you can relax as of now! Great job mate! Do provide the details that I have mentioned in the previous comment! Thank you :)

**Comment by vatsal-afk** [comment]
hi, i closed the PR and will open a new one with the changes you asked for

**Comment by Circuit-Overtime** [comment]
alright buddy, no problem

**Comment by vatsal-afk** [comment]
Here are my details:
E-mail: vtsl5819@gmail.com
LinkedIn: https://www.linkedin.com/in/vatsal-agarwal-b67315280/

**Comment by Circuit-Overtime** [comment]
alright

**Comment by Circuit-Overtime** [comment]
the file has been added and approved, and will be implemented in the main server! Thanks Vastal

**Comment by vatsal-afk** [comment]
thanks a lot!
